export const places = {
    countries: [
        // Africa
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Democratic Republic of the Congo",
        "Republic of the Congo",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Eswatini",
        "Ethiopia",
        "Gabon",
        "The Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Ivory Coast",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Mauritania",
        "Morocco",
        "Namibia",
        "Niger",
        "Nigeria",
        "Rwanda",
        "São Tomé and Príncipe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sudan",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Western Sahara",
        "Zambia",
        "Zimbabwe",

        // North & Central America + Caribbean
        "Antigua and Barbuda",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Belize",
        "Bermuda",
        "Canada",
        "Cayman Islands",
        "Costa Rica",
        "Cuba",
        "Dominica",
        "Dominican Republic",
        "El Salvador",
        "Greenland",
        "Grenada",
        "Guatemala",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Mexico",
        "Montserrat",
        "Netherlands Antilles",
        "Nicaragua",
        "Panama",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint-Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
        "United States",
        "British Virgin Islands",
        "United States Virgin Islands",
        "Puerto Rico",

        // South America
        "Argentina",
        "Bolivia",
        "Brazil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Uruguay",
        "Venezuela",

        // Asia
        "Afghanistan",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Bhutan",
        "Brunei",
        "Burma",
        "Cambodia",
        "China",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Israel",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "North Korea",
        "South Korea",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Lebanon",
        "Malaysia",
        "Maldives",
        "Mongolia",
        "Nepal",
        "Oman",
        "Pakistan",
        "The Philippines",
        "Qatar",
        "Russia",
        "Saudi Arabia",
        "Singapore",
        "Sri Lanka",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Turkey",
        "Turkmenistan",
        "United Arab Emirates",
        "Uzbekistan",
        "Vietnam",
        "Yemen",

        // Europe
        "Albania",
        "Andorra",
        "Armenia",
        "Austria",
        "Azerbaijan",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Georgia (country)",
        "Germany",
        "Greece",
        "Hungary",
        "Iceland",
        "Ireland",
        "Italy",
        "Kazakhstan",
        "Kosovo",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Malta",
        "Moldova",
        "Montenegro",
        "Netherlands (by province)",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "San Marino",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "Turkey",
        "Ukraine",
        "United Kingdom",

        // Oceania
        "Australia",
        "East Timor",
        "Fiji",
        "Indonesia",
        "Kiribati",
        "Papua New Guinea",
        "Marshall Islands",
        "Federated States of Micronesia",
        "Nauru",
        "New Zealand",
        "Palau",
        "Samoa",
        "Solomon Islands",
        "Tonga",
        "Tuvalu",
        "Vanuatu"
    ],
    cities: [
        "Tokyo",
        "Jakarta",
        "Delhi",
        "Guangzhou",
        "Mumbai",
        "Manila",
        "Shanghai",
        "Seoul",
        "Cairo",
        "Mexico City",
        "Kolkata",
        "São Paulo",
        "New York",
        "Karachi",
        "Dhaka",
        "Beijing",
        "Chongqing",
        "Lagos",
        "Istanbul",
        "Ho Chi Minh City",
        "Lahore",
        "Bangalore",
        "Paris",
        "Bogotá",
        "Chennai",
        "Lima",
        "Bangkok",
        "Seoul",
        "Nagoya",
        "Hyderabad",
        "London",
        "Chicago",
        "Chengdu",
        "Nanjing",
        "Wuhan",
        "Harbin",
        "Houston",
        "Dallas",
        "Miami",
        "Atlanta",
        "Philadelphia",
        "Washington, D.C.",
        "Phoenix",
        "San Antonio",
        "San Diego",
        "San Jose",
        "Austin",
        "Indianapolis",
        "Jacksonville",
        "Columbus",
        "Fort Worth",
        "Charlotte",
        "Detroit",
        "El Paso",
        "Memphis",
        "Boston",
        "Seattle",
        "Denver",
        "Nashville",
        "Oklahoma City",
        "Portland",
        "Las Vegas",
        "Louisville",
        "Baltimore",
        "Milwaukee",
        "Albuquerque",
        "Tucson",
        "Fresno",
        "Sacramento",
        "Mesa",
        "Kansas City",
        "Long Beach",
        "Colorado Springs",
        "Raleigh",
        "Omaha",
        "Oakland",
        "Minneapolis",
        "Tulsa",
        "Arlington",
        "New Orleans",
        "Wichita",
        "Cleveland",
        "Bakersfield",
        "Aurora",
        "Anaheim",
        "Honolulu",
        "Santa Ana",
        "Riverside",
        "Corpus Christi",
        "Lexington",
        "Henderson",
        "Stockton",
        "Saint Paul",
        "Cincinnati",
        "St. Louis",
        "Pittsburgh",
        "Greensboro",
        "Anchorage",
        "Plano",
        "Lincoln",
        "Orlando",
        "Irvine",
        "Newark",
        "Durham",
        "Chula Vista",
        "Fort Wayne",
        "Jersey City",
        "Madison",
        "Lubbock",
        "Chesapeake",
        "Garland",
        "Glendale",
        "Hialeah",
        "Baton Rouge",
        "Laredo",
        "Chattanooga",
        "Macon",
        "Huntsville",
        "Montgomery",
        "Akron",
        "Shreveport",
        "Mobile",
        "Jackson",
        "Cape Coral",
        "Peoria",
        "Springfield",
        "Eugene",
        "Salem",
        "Lancaster",
        "Beaumont",
        "Odessa",
        "College Station",
        "Victoria",
        "Cedar Rapids",
        "Waterloo",
        "Davenport",
        "Muscatine",
        "Bettendorf",
        "Moline",
        "Rock Island",
        "Dubuque",
        "Sioux City",
        "Sioux Falls",
        "Rapid City",
        "Pierre",
        "Mitchell",
        "Brookings",
        "Aberdeen",
        "Watertown",
        "Milbank",
        "Redwood Falls",
        "Marshall",
        "Worthington",
        "Luanda",
        "Addis Ababa",
        "Dar es Salaam",
        "Kinshasa",
        "Abidjan",
        "Accra",
        "Nairobi",
        "Kigali",
        "Douala",
        "Yaoundé",
        "Libreville",
        "Port Harcourt",
        "Banjul",
        "Conakry",
        "Freetown",
        "Monrovia",
        "Bujumbura",
        "Kampala",
        "Khartoum",
        "Juba",
        "Asmara",
        "Djibouti",
        "Mogadishu",
        "Zanzibar",
        "Moroni",
        "Port Louis",
        "Victoria",
        "Antananarivo",
        "Maputo",
        "Windhoek",
        "Gaborone",
        "Harare",
        "Lusaka",
        "Blantyre",
        "Lilongwe",
        "Mbeya",
        "Mwanza",
        "Mombasa",
        "Kisumu",
        "Lubumbashi",
        "Mbuji-Mayi",
        "Kananga",
        "Mbandaka",
        "Goma",
        "Bukavu",
        "Hargeisa",
        "Berbera",
        "Ulaanbaatar",
        "Santiago",
        "Minsk",
        "Bucharest",
        "Warsaw",
        "Moscow",
        "Berlin",
        "Rome",
        "Vienna",
        "Madrid",
        "London",
        "Barcelona",
        "Paris",
        "Belgrade",
        "Athens",
        "Munich",
        "Oslo",
        "Stockholm",
        "Helsinki",
        "Prague",
        "Zagreb",
        "Copenhagen",
        "Brussels",
        "Vilnius",
        "Sarajevo",
        "Belgrade",
        "Ljubljana",
        "Porto",
        "Florence",
        "Milan",
        "Amsterdam",
        "Geneva",
        "Zurich",
        "Luxembourg City",
        "Antwerp",
        "Marseille",
        "Athens",
        "Dublin",
        "Edinburgh",
        "Glasgow",
        "Brussels",
        "Rome",
        "St. Petersburg",
        "London",
        "Paris",
        "Manchester",
        "Munich",
        "Hamburg",
        "Istanbul",
        "Berlin",
        "Frankfurt",
        "Madrid"
    ]
}