export const cities = [
    "Tokyo, Japan",
    "Osaka, Japan",
    "Nagoya, Japan",
    "Fukuoka, Japan",
    "Shizuoka, Japan",
    "Sapporo, Japan",
    "Kawasaki, Japan",
    "Kobe, Japan",
    "Kyoto, Japan",
    "Hiroshima, Japan",
    "Sendai, Japan",
    "Saitama, Japan",
    "Chiba, Japan",
    "Niigata, Japan",
    "Hamamatsu, Japan",

    "Delhi, India",
    "Mumbai, India",
    "Bangalore, India",
    "Kolkata, India",
    "Chennai, India",
    "Hyderabad, India",
    "Ahmedabad, India",
    "Pune, India",
    "Surat, India",
    "Jaipur, India",
    "Lucknow, India",
    "Kanpur, India",
    "Indore, India",
    "Nagpur, India",
    "Coimbatore, India",

    "Shanghai, China",
    "Beijing, China",
    "Chongqing, China",
    "Tianjin, China",
    "Guangzhou, China",
    "Shenzhen, China",
    "Chengdu, China",
    "Nanjing, China",
    "Wuhan, China",
    "Hangzhou, China",
    "Foshan, China",
    "Dongguan, China",
    "Xi An Shaanxi, China",
    "Harbin, China",
    "Zhengzhou, China",

    "Dhaka, Bangladesh",
    "Chittagong, Bangladesh",

    "Sao Paulo, Brazil",
    "Rio De Janeiro, Brazil",
    "Belo Horizonte, Brazil",
    "Brasilia, Brazil",
    "Fortaleza, Brazil",
    "Recife, Brazil",
    "Porto Alegre, Brazil",
    "Salvador, Brazil",
    "Curitiba, Brazil",
    "Campinas, Brazil",
    "Goiania, Brazil",
    "Belem, Brazil",
    "Manaus, Brazil",
    "Sao Luis, Brazil",
    "Natal, Brazil",

    "Cairo, Egypt",
    "Alexandria, Egypt",

    "Mexico City, Mexico",
    "Guadalajara, Mexico",
    "Monterrey, Mexico",
    "Puebla, Mexico",
    "Toluca De Lerdo, Mexico",

    "Karachi, Pakistan",
    "Lahore, Pakistan",
    "Faisalabad, Pakistan",
    "Rawalpindi, Pakistan",
    "Multan, Pakistan",
    "Peshawar, Pakistan",
    "Quetta, Pakistan",
    "Gujranwala, Pakistan",
    "Sialkot, Pakistan",
    "Hyderabad, Pakistan",
    "Islamabad, Pakistan",
    "Bahawalpur, Pakistan",
    "Sargodha, Pakistan",
    "Sukkur, Pakistan",
    "Larkana, Pakistan",

    "Kinshasa, DR Congo",
    "Mbuji Mayi, DR Congo",
    "Lubumbashi, DR Congo",

    "Lagos, Nigeria",
    "Kano, Nigeria",
    "Ibadan, Nigeria",
    "Port Harcourt, Nigeria",
    "Abuja, Nigeria",
    "Benin City, Nigeria",
    "Maiduguri, Nigeria",
    "Zaria, Nigeria",
    "Aba, Nigeria",
    "Jos, Nigeria",
    "Ilorin, Nigeria",
    "Oyo, Nigeria",
    "Enugu, Nigeria",
    "Abeokuta, Nigeria",
    "Onitsha, Nigeria",

    "Istanbul, Turkey",
    "Ankara, Turkey",
    "Izmir, Turkey",
    "Bursa, Turkey",
    "Adana, Turkey",
    "Gaziantep, Turkey",
    "Konya, Turkey",
    "Antalya, Turkey",
    "Kayseri, Turkey",
    "Mersin, Turkey",
    "Diyarbakir, Turkey",
    "Samsun, Turkey",
    "Eskişehir, Turkey",
    "Malatya, Turkey",
    "Erzurum, Turkey",

    "Buenos Aires, Argentina",
    "Cordoba, Argentina",
    "Rosario, Argentina",
    "Mendoza, Argentina",
    "La Plata, Argentina",

    "Manila, Philippines",
    "Quezon City, Philippines",
    "Davao City, Philippines",
    "Caloocan, Philippines",
    "Cebu City, Philippines",

    "Jakarta, Indonesia",
    "Surabaya, Indonesia",
    "Bandung, Indonesia",
    "Bekasi, Indonesia",
    "Depok, Indonesia",

    "Tehran, Iran",
    "Mashhad, Iran",
    "Isfahan, Iran",
    "Karaj, Iran",
    "Shiraz, Iran",

    "Paris, France",
    "Marseille, France",
    "Lyon, France",
    "Toulouse, France",
    "Nice, France",

    "London, United Kingdom",
    "Manchester, United Kingdom",
    "Birmingham, United Kingdom",
    "Leeds, United Kingdom",
    "Glasgow, United Kingdom",

    "Seoul, South Korea",
    "Busan, South Korea",
    "Incheon, South Korea",
    "Daegu, South Korea",
    "Daejeon, South Korea",

    "New York, United States",
    "Los Angeles, United States",
    "Chicago, United States",
    "Houston, United States",
    "Phoenix, United States",
    "New York City, New York",
    "Los Angeles, California",
    "Chicago, Illinois",
    "Houston, Texas",
    "Phoenix, Arizona",
    "San Antonio, Texas",
    "Philadelphia, Pennsylvania",
    "San Diego, California",
    "Dallas, Texas",
    "Austin, Texas",
    "Jacksonville, Florida",
    "San Jose, California",
    "Fort Worth, Texas",
    "Columbus, Ohio",
    "Charlotte, North Carolina",
    "Indianapolis, Indiana",
    "San Francisco, California",
    "Seattle, Washington",
    "Denver, Colorado",
    "Oklahoma City, Oklahoma",
    "Nashville, Tennessee",
    "El Paso, Texas",
    "Washington, District of Columbia",
    "Boston, Massachusetts",
    "Las Vegas, Nevada",
    "Portland, Oregon",
    "Detroit, Michigan",
    "Memphis, Tennessee",
    "Louisville, Kentucky",
    "Baltimore, Maryland",
];